bootstrapworld/codemirror-blocks

example/wescheme-example.js
=> Add extraKey configuration to cm2 ( inserts (...)

package.json, spec/blocks-test.js, spec/events.js, spec/parsers/primitives-test.js, spec/ui/Editor-test.js, spec/ui/PrimitiveBlock-test.js, spec/ui/Toolbar-test.js, src/blocks.js, src/parsers/primitives.js, src/parsers/wescheme/index.js, src/ui/Editor.js, src/ui/PrimitiveBlock.js, src/ui/PrimitiveList.js, src/ui/Toolbar.js, src/ui/index.js
Add support for dragging literals from the toolbar into the editor.
=> Toolbar drag

package.json, spec/events.js, spec/ui/Editor-test.js, spec/ui/TrashCan-test.js, src/blocks.js, src/ui/Editor.js, src/ui/Editor.less, src/ui/TrashCan.js, src/ui/TrashCan.less, src/ui/index.js
One step closer to closing #23
=> drag nodes onto toolbar to delete

CHANGELOG.md
Added a changelog file and filled it.
=> Benjamin limpich first task

src/Renderer.js, src/languages/index.js, src/ui/PrimitiveBlock.js
=> Add optional printASTNode function to renderOptions

.eslintrc, example/editor-example.js, example/editor.html, src/languages/index.js
These changes were made by @farmanrl, I just fixed up the pull request branch to be a bit cleaner.
=> Add language selector in editor example

spec/languages/lambda/lambda-parser-test.js, src/ast.js, src/languages/lambda/ast.js, src/languages/lambda/index.js, src/languages/lambda/parser.js, src/languages/lambda/style.less, src/languages/lambda/templates/prog.handlebars
Courtesy of @farmanrl and @blimpich
=> Add initial version of the lambda language

karma.conf.js, spec/languages/wescheme/WeschemeParser-test.js, src/Renderer.js, src/ast.js, src/languages/wescheme/WeschemeParser.js, src/languages/wescheme/style.less, src/templates/ifExpression.handlebars
=> Add if blocks

example/ast-test.rkt, example/wescheme-example.js, spec/languages/wescheme/WeschemeParser-test.js, src/Renderer.js, src/ast.js, src/languages/wescheme/WeschemeParser.js, src/languages/wescheme/style.less, src/templates/condClause.handlebars, src/templates/condExpression.handlebars, src/templates/node.handlebars
=> implement cond expression support

example/ast-test.rkt, spec/languages/wescheme/WeschemeParser-test.js, src/Renderer.js, src/ast.js, src/languages/wescheme/WeschemeParser.js, src/languages/wescheme/style.less, src/templates/lambdaExpression.handlebars
=> Add support for lambda blocks

.babelrc, .gitignore, .travis.yml, README.md, package.json
Note: do not merge. Need to merge https://github.com/bootstrapworld/wescheme-js/pull/9 first
=> Use babel-preset-env and switch from yarn to npm

.eslintrc, example/cow-game.js, example/editor-example.js, example/editor.html, example/example-page.less, example/example.js, example/fullscheme-example.js, example/space-invaders.js, example/wescheme-example.js, spec/blocks-test.js, spec/focus-test.js, spec/wescheme-parser-test.js, src/blocks.js, src/languages/wescheme/WeschemeParser.js, src/ui/Editor.js, src/ui/Search.js, src/ui/index.js, src/ui/searchers/ByBlock.js, src/ui/searchers/ByString.js
Also add immediate visual response to search failure.
Note that this reactify is orthogonal to the reactify branch.
=> Get search working with editor.html and reactify editor.html

spec/blocks-test.js, spec/focus-test.js, src/blocks.js, src/languages/wescheme/WeschemeParser.js
This PR tracks work on the quarantine code. That means:
- code cleanup
- an attempt to fix #139 and #147 
- decoupling the quarantine from React and the Renderer
=> [WIP] Redo quarantines

.eslintrc, src/languages/pyret/PyretParser.js
and alphabetize rules.
Hopefully this should make Hound less noisy.
=> add ignore patterns for vars and args

webpack/test.config.js
Mostly generating this PR to test the build output..
=> Better coverage reports

example/editor-example.js, karma.conf.js, src/keymap.js, webpack/base.config.js, webpack/bundle.config.js, webpack/example.config.js
Now `npm run lint` is happy again.
=> Fix outstanding lint errors/warnings

src/keymap.js, src/ui/BlockEditor.tsx, src/ui/TextEditor.js, src/ui/ToggleEditor.tsx
I'll be adding commits to this over time, with the goal of correctly embracing React's state model as per @pcardune 's review.
=> Component cleanup

src/actions.ts, src/components/ContentEditable.tsx, src/components/Node.tsx, src/edits/commitChanges.ts, src/edits/fakeAstEdits.ts, src/edits/performEdits.ts, src/keymap.tsx, src/store.ts, src/ui/BlockEditor.tsx, src/ui/DragAndDropEditor.tsx, src/ui/ToggleEditor.tsx, src/utils.ts
This was a wild ride! Comments inline.
=> Add types to a bunch more code

src/components/NodeEditable.tsx
In my continuing effort to make the code more intelligible, I'm trying to remove the use of instance properties on react components that are not needed. First up is the `cachedValue` property of NodeEditable.
The NodeEditable component is trying to act like a stateless component, forcing its parent to hold the edit state of the node's text value using the `value` and `onChange` props. But NodeEditable actually cares about the state, and the fact that the state has changed, so it can skip actually editing the node in saveEdit if it hasn't changed from it's original form. Instead of also pushing that responsibility up the tree, it holds on to the initial value of the ast node with `cachedValue`, and then looks at it in saveEdit.
I don't know why NodeEditable needs a parent component to hold …
=> Get rid of cachedValue property on NodeEditable

src/components/ContentEditable.tsx
Now that we don't use shouldComponentUpdate, there is no reason for this to not be a pure functional component.
=> make ContentEditable a functional component

src/components/NodeEditable.tsx
The hard part was figuring out the purpose of `ignoreBlur` and how to get rid of it. This depends on #405
=> Make NodeEditable a functional component

src/components/NodeEditable.tsx
* Remove dead code in NodeEditable onSuccess handler
* Break out parts of saveEdit that don't have to do with the react component
* move setAfterDOMUpdate for focusSelf outside of component
* Use a better method to prevent double edits when pressing enter on a node editable
* move saveEdit and handleKeyDown into render function to make it clear that they are not used outside of render
* Make NodeEditable a functional component
* Simplify to reduce the size of the diff
=> Make NodeEditable a functional component (#406)

src/components/Dialog.tsx
Proceeding cautiously, so I'm tackling something small before trying Toolbar....
=> move Dialog component over to hooks

src/components/NodeEditable.tsx
`mapDispatchToProps` is replaced by `useDispatch`, and `mapStateToProps` becomes `useSelector`.
The best part about this change is that the props of NodeEditable only contain the actual props that are passed in from the parent component, and all the stuff that is redux specific lives inside the component.
=> Use redux hooks api in favor of connect()

src/actions.ts, src/components/NodeEditable.tsx, src/reducers.ts
Just some small changes to types I made while perusing the code.
=> Better types for onDisableEditable and RootState.editable

src/components/DropTarget.tsx
Next step will be to glue these together into a single component.
=> Use redux and react-dnd hooks API in favor of the HOCs

src/components/Node.tsx
I got as far as converting the redux and react-dnd higher order components to using the corresponding hooks api. Next step is to unravel the store.onKeyDown business, which requires that components have a certain interface.
=> Work towards making Node a functional component

src/edits/commitChanges.ts, src/edits/performEdits.ts, src/reducers.ts, src/toolkit/debug.ts, src/ui/EditorButtons.tsx
Just getting rid of a TODO I left behind.
=> Stop storing reducerActivities on global window object

packages/codemirror-blocks/spec/ui/Node-test.tsx, packages/codemirror-blocks/src/ast.ts, packages/codemirror-blocks/src/components/Node.tsx, packages/codemirror-blocks/src/keymap.tsx, packages/codemirror-blocks/src/nodes.tsx
Also did a bit of refactoring of comment id generation and removed the unnecessary `isLocked` function that was being passed down to `keyDown.`
=> Add tests for comment rendering in Node

packages/codemirror-blocks/spec/performEdits-test.ts, packages/codemirror-blocks/src/edits/performEdits.ts
=> Make OverwriteEdit take comments into account

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Just prettifying the issue templates that github generated
=> prettify issue templates

package-lock.json, packages/codemirror-blocks/package.json
It's not being used anymore...
=> Remove unused plugin-proposal-decorators dep

packages/codemirror-blocks/spec/comment-test.ts, packages/codemirror-blocks/src/toolkit/test-utils.tsx
=> Reenable comment insertion tests

packages/codemirror-blocks/spec/activation-test.ts, packages/codemirror-blocks/src/components/Node.tsx, packages/codemirror-blocks/src/state/actions.ts
=> Fix focus restoration after node edit
