.eslintrc
Sadly, hound doesn't understand that each directory can have its own
eslint config. So we have to combine the eslint configs with the spec
eslint config :(
=> Fix hound lint complaints

src/ast.js, src/blocks.js, src/components/Node.js
So this is a working proof of concept that shows how to get nodes to remain collapsed after editing other nodes. For any UI state that needs to be sticky across edits, the following must occur:
1. The state for that UI must be stored directly on the AST node
2. The AST node that has that state must get _patched_ rather than blown away by the parser
3. The react component that renders that node must look at the state stored on the node when deciding how to render the node.
The render loop looks like this:
0. parse codemirror text into AST
1. render AST using react components
2. attach various events to rendered dom nodes
3. user collapses a node in the tree
3a. dom is updated to reflect user's action
3b. AST node is updated to reflect user's action
4. user goes through edit flow for a …
=> Make collapsing nodes sticky

spec/ast-test.js, spec/languages/wescheme/WeschemeParser-test.js, spec/wescheme-parser-test.js, src/Renderer.js, src/ast.js, src/components/Sequence.js, src/languages/wescheme/WeschemeParser.js, src/languages/wescheme/style.less
Adds Sequence nodes to the block language and displays WeschemeParser `beginExprs` as Sequence nodes.
(having a little trouble getting the existing test suite to run, so tests are not yet available for the changes in this PR for now)
=> Add Sequences to block language

example/editor-example.js, example/fullscheme-example.js, example/wescheme-example.js, example/wescheme.html, spec/ast-test.js, src/Renderer.js, src/blocks.js, src/components/Blank.js, src/components/CondClause.js, src/components/CondExpression.js, src/components/Expression.js, src/components/FunctionDef.js, src/components/IdentifierList.js, src/components/IfExpression.js, src/components/LambdaExpression.js, src/components/Literal.js, src/components/Node.js, src/components/Sequence.js, src/components/StructDef.js, src/components/Unknown.js, src/components/VariableDef.js, src/languages/wescheme/components/LetLikeExpr.js, src/languages/wescheme/components/WhenUnlessExpr.js, src/languages/wescheme/style.less, src/less/blocks.less
Move over the non-patching improvements from the speed branch.
- Use CM's viewport
- Improvements to `render()`, allowing it to handle non-root nodes
- Use `node.type` to derive className in React Components, eliminating the need to pass around `type` as an argument
- Improvements to `animateTransition()`
=> Optimization

spec/ast-test.js, src/Renderer.js, src/ast.js, src/blocks.js, src/components/CodeMirrorContainer.jsx, src/components/Node.jsx, src/languages/example/ExampleParser.js, src/languages/example/components/Literal.jsx
Partly addresses #112 
**NOT DONE** quarantine nodes still create a toplevel React node that's rendered using `ReactDOM.render()` into some poor victim DOM node.
:large_blue_circle:  Now you're thinking with Portals! :red_circle: 
So the basic idea is to create a DOM tree and a React component tree like this.
DOM Tree
```
<textarea></textarea>
<CodeMirror wrapper element>...</code mirror>
<span class="code-mirror-react-root-container"/>
```
And into the code mirror React root container we render this React tree:
```
<CodeMirrorContainer>
<React.Portal target="code mirror root marker 1">
<Node node="root 1" />
</React.Portal>
<React.Portal target="code mirror root marker 2">
<Node node="root 2" />
</React.Portal>
</CodeMirrorContainer>
```
The invariant is that for every root AST node in …
=> Reactify - try and use the normal render cycle for drawing blocks

src/CodeMirrorBlocks.js, src/ui/BlockEditor.js, src/ui/TextEditor.js, src/ui/ToggleEditor.js
This has required adding some proptypes to both BlockEditor and TextEditor so that ToggleEditor has access to the mounted editor.
=> Move duplicate code to ToggleEditor

doc/language.md, src/actions.js, src/components/Args.jsx, src/components/ContentEditable.js, src/components/DropTarget.jsx, src/components/Node.jsx, src/components/NodeEditable.js, src/dnd.js, src/nodes.jsx, src/reducers.js, src/ui/BlockEditor.js, src/ui/DragAndDropEditor.js
Many changes, that cumulatively result in fixing the issues introduced by the wip-optimization PR:
- Greatly simplify the drop target API. Drop targets no longer need `index` or `location`, Args no longer need `location`, and DropTargetContainers are no longer necessary at all.
- Drop target editing state is now stored in the Redux store, under `editable`.
- Nodes make themselves available to all of their descendants via a context called `NodeContext` with value `{node: _}`.
- DropTargets and DropTargetSiblings find themselves by walking the DOM.
- For annoying reasons, DropTargets need to have their `id` given to them as a prop, so there's now a wrapper Component around DropTargets that exists solely for the purpose of generating a uuidv4 and handing it to the DropTarget.
- The …
=> Droptarget idea

Makefile, package.json, src/languages/pyret/PyretParser.js, src/languages/pyret/PyretParser.ts, src/languages/pyret/ast.js
I added types to Pyret's parser and ast files for documentation purposes. This PR adds a command to watch these files and recompile on changes and a command to beautify the resulting JS files, which differ from the rest of the project in indentation.
=> Automate TSC and formatting resulting JS files

README.md, webpack/bundle.config.js
Using `import .... from "CodeMirror"` should work on machines
with case-insensitive file systems (i.e., OSX), but will throw a
"module could not be found" error on machines with case-sensitive
file systems, where `codemirror` is the correct path.
=> fix incorrect codemirror import

spec/activation-test.js, spec/focus-test.js, src/actions.js, src/ast.ts, src/components/DropTarget.jsx, src/components/Node.jsx, src/edits/commitChanges.js, src/edits/patchAst.js, src/keymap.js, src/ui/BlockEditor.js, src/ui/PrimitiveList.js, src/ui/Toolbar.js
Fixes a regression, where tabbing into the editor failed to focus the first node.
This also cleans up a lot of code in `activateByNid` and elsewhere, using option chaining and some simpler logic. Finally, the actual bug was in `commitChanges`: if the focusHint failed, the `focusId` was set to `undefined`.
=> Focus-on-1st-root when tabbed

example/editor-example.js, spec/activation-test.js, spec/api-test.js, spec/comment-test.js, spec/drag-test.js, spec/focus-test.js, spec/markText-test.js, spec/new-blocks-test.js, spec/support/jasmine.json, spec/ui/Search-test-old.js, spec/undo-redo-test.js, src/toolkit/simulate.ts, src/toolkit/test-utils.ts
This PR completes issue #365.
Now language modules will be able to reuse the code from test-utils by importing from `codemirror-blocks/lib/toolkit/test-utils`, i.e.:
```js
import {wait, teardown, activationSetup} from 'codemirror-blocks/lib/toolkit/test-utils';
```
=> Move test-utils to toolkit directory

src/nodeSpec.ts
This was causing the error `Return type of public method from exported class has or is using name 'ChildrenIterator' from external module ".../codemirror-blocks/src/nodeSpec" but cannot be named.`
Basically, if you export a function to make it available to other modules, but it's return type is a type that hasn't been exported, then typescript will be unhappy. This can pop up seemingly out of nowhere because typescript does so much type inference for you that you often don't need to explicitly specify the return type of a function.
There are a few ways to solve the problem in this particular case:
1. `export class ChildrenIterator` - this would allow other modules to construct a new `ChildrenIterator` themselves without having to go through the `children()` function. This however exposes …
=> fix typescript error about non-exported return type

src/actions.ts, src/edits/performEdits.ts
@pcardune this PR makes the Edit class implementation internal to `performEdits.ts`, exporting only the Interface. I have _no idea_ if this is considered "more correct" in TypeScriptland than what we were already doing.
Is this change a good thing, or am I being too pedantic?
=> only export the interface for the Edit class

package-lock.json, package.json, src/ast.ts, src/edits/fakeAstEdits.ts, src/nodeSpec.ts, src/parsers/primitives.ts, src/reducers.ts, src/store.ts, src/toolkit/debug.ts, src/toolkit/test-utils.ts, src/ui/BlockEditor.tsx, src/ui/Search.tsx, src/ui/ToggleEditor.tsx, tsconfig.json
This change will make it harder to accidentally introduce untyped code by making sure typescript doesn't use type inference to generate the `any` type. You'll still be allowed to use `any`, you'll just have to explicitly say that a variable is `any`.
Most of this PR is just adding types where they were missing. However, there was one larger change that I made for `fakeASTEdits` and `nodeSpec`.
the `nodeSpec` stuff is a combination of a runtime typechecking library and a specification for generating fake ast nodes that look like ones from a particular language module. While it's possible to make the mutations/cloning of nodes statically typechecked using generics, it would be complicated and require changing the way nodespecs work. For example, at the moment you can define a spec for a …
=> Turn on noImplicitAny in typescript config

src/ast.ts, src/components/DropTarget.tsx, src/store.ts, src/toolkit/debug.ts, src/ui/BlockEditor.tsx, src/utils.ts
The changes:
- `nodeCounter`  is no longer attached to the global store
- `gensym` has been renamed to `genUniqueId` which IMO is more explanatory
- `resetNodeCounter` is no longer being exported as part of the public API interface
This  change depends on #387, which should be reviewed first.
=> Rework node id generation to be more encapsulated

karma.conf.js, spec/comment-test.ts, spec/index.js, spec/tsconfig.json, src/toolkit/karma.ts
Turns out there is a bug in karma-webpack v5 that made sourcemaps stop working. I found the workaround in this issue: https://github.com/ryanclark/karma-webpack/issues/493.
I think in theory this might make running the tests a bit slower, but I didn't notice any difference in performance when I tried it out locally.
=> Enable typescript for test files and fix sourcemaps

src/actions.ts
See explanation in [this comment](https://github.com/bootstrapworld/codemirror-blocks/issues/391#issuecomment-914529405).
=> Fix erroneous test failures for focus() call being undefined

src/actions.ts, src/dnd.ts, src/edits/commitChanges.ts, src/edits/performEdits.ts, src/edits/speculateChanges.ts, src/shared.ts, src/ui/BlockEditor.tsx, src/ui/TextEditor.tsx, src/ui/ToggleEditor.tsx, src/ui/TrashCan.tsx
Just doing some more refactoring to try and clean up this tangle.
Now SHARED.parse only gets initialized inside ToggleEditor, and is now only accessed by redux actions,  longer being accessed except from a react component or a redux action and the top-level editor components.
Also in this PR is refactoring of TrashCan to be a functional component, which uses the react-dnd hooks api. It's a lot more compact.
=> Make TrashCan a functional component and try to unwind use of SHARED.parse

src/components/ContentEditable.tsx
I'm looking more closely at some of these "leaf" components to see if they can be simplified. I tried to figure out why the `ContentEditable` component needed a custom `shouldComponentUpdate` method but I couldn't figure it out just reading the code. So I removed it and the tests still passed. Usually `shouldComponentUpdate` is strictly used for performance tuning in rare cases. Is that the case here?
=> remove shouldComponentUpdate from ContentEditable

package-lock.json, package.json, src/components/ContentEditable.tsx, src/components/NodeEditable.tsx
I found the reason why we were using `shouldComponentUpdate` and it has to do with some subtle things in react's update model and contenteditable dom nodes. See https://stackoverflow.com/questions/22677931/react-js-onchange-event-for-contenteditable/27255103#27255103.
This PR switches us to using the I've switched us to using the [react-contenteditable](https://github.com/lovasoa/react-contenteditable) npm package which implements these intricacies, is well maintained, used by many, and has actual unit tests for this subtle behavior.
=> Use react-contenteditable instead of our own solution

src/components/ContentEditable.tsx, src/components/NodeEditable.tsx
We were using this `itDidMount` prop to pass the inner span element to the parent component. But this behavior is already supported by react ref objects using [React.forwardRef](https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-to-dom-components), which also ensures that the code that uses the element is always using the latest one (via the `RefObject.current` property).
=> use React.forwardRef in favor of itDidMount callback

src/components/NodeEditable.tsx
Now that we are using refs, react can tell us about whether the element we are referring to still exists or not, which we should use to avoid doing unnecessary work. The tests started failing because we were not doing this check.
=> Fix tests 

src/components/NodeEditable.tsx, src/utils.ts
also fixed a bug with cancelAfterDOMUpdate never cancelling the requestAnimationFrame callback.
Wherever we use `setAfterDOMUpdate`, there should be a comment explaining why it is necessary. I bet there are a lot of places (i found one in this PR) where it is not necessary, and having it just causes subtle race conditions to occur.
=> Remove unnecessary use of setAfterDOMUpdate in NodeEditable

.github/workflows/lint.yml, src/ui/Toolbar.tsx
Looks like it was set to just js files before and I forgot to update it when moving everything to typescript.
=> Enable linting of typescript files in github lint check workflow

.babelrc.json, src/components/DropTarget.tsx
1. extract `getLocation()` to make the DropTarget component have a smaller surface area
2. remove `isDropTarget` class property which doesn't appear to be used or needed
3. remove the constructor
4. move event handler functions into render function
=> Preparatory work for converting DropTarget to use hooks

src/components/DropTarget.tsx, src/components/Node.tsx
Got to remove a lot of cruft here. Now there is just one DropTarget component and not many nested components that only exist to augment props.
=> Make DropTarget into a functional component and ditch the redux/dnd wrappers

src/actions.ts, src/components/NodeEditable.tsx, src/shared.ts, src/ui/BlockEditor.tsx, src/ui/ToggleEditor.tsx
`recordedMarks` was only ever used by ToggleEditor, so I moved it to be an instance property on ToggleEditor. It should probably be stored in some different way but my goal for the time being was just to get it off SHARED.
`getExceptionMessage` was just broken. It never got set and was accessed in two different places. It looks like it was replaced with a property of the same name on the language definition object, but then wasn't removed from the SHARED object. As a result, the error messaging was broken. I fixed it. There weren't any tests for this, but it seems like there should be since this is very much a user facing feature. What's the best place to add tests for parse error handling?
`buffer` was only used by actions.ts for copy/paste handling, so I moved the creation and storage …
=> Remove some dead stuff from SHARED global

src/toolkit/test-utils.ts, src/ui/BlockEditor.tsx, src/utils.ts
Now calls to `afterDOMUpdate()` keep track of all uncompleted callbacks, allowing you to wait for all uncompleted callbacks to finish.
This should take care of the first todo in #391
=> Remove 100ms delay in tests

src/components/Node.tsx, src/components/NodeEditable.tsx, src/keymap.tsx
So in this PR, I took the node class, which now consisted of just a render method and some lifecycle methods, and made it into a functional component, but I got stymied in a couple places.
1. the class component extends `BlockComponent` which has a shouldComponentUpdate method. Something is depending on the exact implementation of that shouldComponentUpdate method (i.e. it's not purely a performance enhancement), and the tests fail when I try to remove it.
2. the `componentDidUpdate` lifecycle method depends on the previous props, which doesn't really map onto the way `useEffect()` works.
To deal with the above issues, I left in a `BlockComponentNode` component that wraps the functional `Node` component to get the lifecycle methods. This is not great and I'd like to figure out how to not …
=> Get a bit closer to making Node a functional component

src/components/Node.tsx, src/keymap.tsx, src/store.ts, src/ui/BlockEditor.tsx, src/ui/ToggleEditor.tsx
1. Node.tsx and BlockEditor.tsx now call `keyDown()` directly instead of it being routed through `store.onKeyDown`.
2. keydown handlers do not use `this` anymore, and instead take a typesafe env object.
3. BlockEditor.tsx only passes what keyDown actually needs, and not its whole instance
4. The keydown env object is not longer a bunch of component props, dispatch wrappers, and random functions mashed together into a single object.
5. A few bugs were found and fixed:
- using arrow keys on the node preview after selecting something in the toolbar would spew errors in the log. now it just beeps.
- up and down arrow keys when not focused on a node spewed errors and didn't do anything. Now they work.
It seems like someone was trying to (or preparing to) do something much more complicated than …
=> Bring some sanity to keyDown event handling

spec/activation-test.ts, spec/api-test.ts, spec/comment-test.ts, spec/drag-test.ts, spec/focus-test.ts, spec/markText-test.ts, spec/new-blocks-test.ts, spec/undo-redo-test.ts, src/toolkit/test-utils.ts, src/utils.ts
Found another test/async problem. Sometimes tests would call functions that would call afterDOMUpdate, then the test would finish, then the next test would run, and then the callback from the previous test would execute, potentially affecting the state of the current test.
This PR fixes the issue by cancelling all outstanding afterDOMUpdate callbacks during teardown.
There is also some other minor cleanup that does not change any behavior: 
- removing unused arguments to finishRender()) 
- passing teardown directly to afterEach, instead of wrapping it in its own function
=> cancel all outstanding dom updates in teardown

src/CodeMirrorBlocks.tsx, src/components/Dialog.tsx, src/ui/Search.tsx, src/ui/ToggleEditor.tsx
`Modal.setAppElement()` should only be called once for the entire application, so arguably it shouldn't even be called from codemirror-blocks since codemirror-blocks isn't an application, but a library that gets embedded in an application. This PR at least brings us closer to the ideal of `setAppElement` being called by the embedding application by moving the call to the entry point to codemirror-blocks.
=> Stop passing appElement through numerous component layers just for Modal.setAppElement

packages/codemirror-blocks/spec/nodeSpec-test.ts, packages/codemirror-blocks/src/nodeSpec.ts, packages/codemirror-blocks/src/nodes.tsx, packages/wescheme-blocks/spec/languages/wescheme/WeschemeParser-test.js, packages/wescheme-blocks/src/languages/wescheme/WeschemeParser.js, packages/wescheme-blocks/src/languages/wescheme/ast.tsx
I discovered a regression where editing a single node in the example wasn't working. The regression was introduced with #534 or #535 when we started generating the hashes for a node lazily. The error that came up was something like this:
1. try to generate a hash for an ASTNode using node spec hash iterator
2. try generating a hash for a specific field in the node using `hashObject`
3. try generating a stable string using `objToStableString`
--- BOOM --- `objToStableString` doesn't work on objects with reference cycles in them. It was trying to convert an ASTNode object, which I guess still has internal cycles :cry: despite my attempts to remove them.  (maybe in `element`?)
ASTNode cyclicness aside, it's weird that we would try to use objToStableString to hash an ASTNode, rather than …
=> Make value node spec less permissive

packages/codemirror-blocks/src/CodeMirror-api.tsx, packages/codemirror-blocks/src/toolkit/debug.ts, packages/codemirror-blocks/src/ui/BlockEditor.tsx, packages/codemirror-blocks/src/ui/ToggleEditor.tsx
This commit bundles executeAction into the `buildAPI` function, which is moved to a separate file.
=> Move CM API to a separate file, re-enable executeAction (490+488)

packages/codemirror-blocks/src/ui/EditorButtons.tsx
Closes #487 
Aside from browser information, what other info would we want to automatically include in the bug report? I opted not to add the redux action log, since it is potentially very large and the only way to include it in the issue is for it to be part of the body text.
=> Make the bug report button open a link to github issues

packages/codemirror-blocks/src/CodeMirror-api.tsx, packages/codemirror-blocks/src/components/NodeEditable.tsx, packages/codemirror-blocks/src/keymap.tsx, packages/codemirror-blocks/src/state/actions.ts, packages/codemirror-blocks/src/utils.ts
There were a number of redux action creators in actions.ts that were only ever dispatched from CodeMirror-api.ts. They were also fairly obfuscated. This PR moves that code out of actions.ts and into CodeMirror-api.ts, while also reducing the "cyclomatic complexity" of that code.
=> Refactor and move codemirror api shim for selection functions out of redux area

packages/codemirror-blocks/spec/activation-test.ts, packages/codemirror-blocks/spec/api-test.ts, packages/codemirror-blocks/src/state/actions.ts
There isn't a good reason AFAICT why activateByNid should be asynchronous. In this PR, I'm going to try to remove the use of `setAfterDOMUpdate()` from `activateByNid()`
=> Move setFocusedNode call outside setAfterDOMUpdate

package-lock.json, packages/wescheme-blocks/package.json
@pcardune I've removed/updated the two packages in wescheme-blocks that were deprecated (polyfill and babel-eslint), and the other warnings are no longer present (I think we've updated webpack-dev-server in the meantime).
=> update/remove outdated wescheme-blocks dependencies (fixes #510)

packages/codemirror-blocks/src/copypaste.ts, packages/codemirror-blocks/src/ui/PrimitiveList.tsx
Both call sites ensure that there's an active node, so there's no need to check if a node is active (or throw an exception if it's not). I've added a comment to document this.
=> Remove copy() exception

packages/codemirror-blocks/src/ast.ts, packages/codemirror-blocks/src/components/Node.tsx, packages/codemirror-blocks/src/edits/fakeAstEdits.ts, packages/codemirror-blocks/src/edits/patchAst.ts, packages/codemirror-blocks/src/edits/performEdits.ts, packages/codemirror-blocks/src/toolkit/test-utils.tsx
Make more properties of ASTNode readonly. This is for #412.
The main change here is that the `element` property is now a readonly getter which looks up the correct element in a mapping using the node's id. Now the only mutable properties left on ASTNode are the following: `id` `nid,` `level`, `ariaSetSize`, and `ariaPosInset`. Of these, `id` is the only one that is mutated outside of annotateNodes.
=> Make more ASTNode properties immutable/readonly

packages/wescheme-blocks/src/wescheme.org.js, packages/wescheme-blocks/webpack.config.js
I just deployed a new build for https://blocks-dot-wescheme-hrd-2.appspot.com/openEditor and noticed that it was broken with the error:
```
Uncaught DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
```
I think this is the right fix, but I couldn't get a local version of wescheme running to test it. Kept getting the following error despite following the README instructions:
```
Buildfile: /home/pcardune/programming/bootstrapworld/wescheme/build.xml
copyjars:
BUILD FAILED
/home/pcardune/programming/bootstrapworld/wescheme/build.xml:28: /home/pcardune/programming/bootstrapworld/wescheme/lib/google-oauth-java-client/libs does not exist.
```
=> fix wescheme.org build and add source maps

packages/codemirror-blocks/spec/undo-redo-test.ts
I was hoping these tests included tests for how focus changes but alas they do not. The code for undo/redo is quite... interesting and these tests don't seem to test any of it. Anyway, this PR reenables the one test that got disabled when we switched to jest.
This is related to #446 and #586
=> reenable/refactor undo-redo  test

packages/codemirror-blocks/spec/state/store-test.ts, packages/codemirror-blocks/src/edits/commitChanges.ts, packages/codemirror-blocks/src/state/actions.ts, packages/codemirror-blocks/src/state/reducers.ts, packages/codemirror-blocks/src/state/selectors.ts, packages/codemirror-blocks/src/ui/BlockEditor.tsx
the `focusHint` parameter that gets passed all over the place was particularly egregious. There is an enormous amount of inconsistency in the values we use to indicate non-values throughout the codebase. `-1`, `false`, `null`, `undefined`... they were all used to mean "nothing". Now we just use `undefined` which is the most natural of all the "non-value" values to use in modern javascript.
=> refactor commitChanges et al. to have more sensible types

packages/cmb-toolkit/src/simulate.ts, packages/codemirror-blocks/spec/activation-test.ts, packages/codemirror-blocks/src/components/Node.tsx, packages/codemirror-blocks/src/components/NodeEditable.tsx, packages/codemirror-blocks/src/editor.ts, packages/codemirror-blocks/src/state/actions.ts, packages/codemirror-blocks/src/ui/ToplevelBlockEditable.tsx
Fixes #591
This ended up being surprisingly complicated. The solution to the actual problem was simple: add a useEffect() that focuses the currently focused node when it mounts. Doing this worked fine and all the tests passed, except there was a cryptic react warning message that showed up when the tests ran. The warning only showed up in tests and not when doing exactly the same thing in the browser.
The issue has to do with the timing of calls to `focus(),` though not the call to `focus()` that I added, but rather one that's been in there already for a while, and which is deeply buried in codemirror in the call to `setBookmark()`. I don't know why the warnings didn't show up until I made this change. In any case, you are theoretically not supposed to monkey with the dom (e.g. by calling …
=> Focus the currently focused node when it mounts

packages/codemirror-blocks/spec/ui/Node-test.tsx, packages/codemirror-blocks/spec/ui/NodeEditable-test.tsx, packages/codemirror-blocks/src/components/Context.tsx, packages/codemirror-blocks/src/components/DropTarget.tsx, packages/codemirror-blocks/src/components/Node.tsx, packages/codemirror-blocks/src/keymap.tsx, packages/codemirror-blocks/src/state/actions.ts, packages/codemirror-blocks/src/state/selectors.ts, packages/codemirror-blocks/src/ui/BlockEditor.tsx, packages/codemirror-blocks/src/ui/DragAndDropEditor.tsx
While trying to understand all the different focusing stuff, I noticed that some elements were being re-rendered even though nothing that they were rendering had changed. For example, editing one node in the ast would cause all other nodes to rerender upon saving the edit.
There were two main culprits:
1. using `useSelector` to get things from the redux store which were only used in event handlers (i.e. not for rendering).
2. selectors that were not memoized, returning a new value every time they were used even though the state used to construct that value hadn't changed.
In making the necessary changes to address these issues, I also did a bit of refactoring in a few places:
- Removing the LanguageContext which was no longer being used after #588 
- Removing `useDropAction`, which was a …
=> Stop rendering nodes that haven't changed after an edit

packages/codemirror-blocks/src/ui/Editor.less, packages/codemirror-blocks/src/ui/PrimitiveList.less
This doesn't appear to change anything in our example, but should improve behavior on WeScheme (and other editors).
=> make codemirror-pane dimensions more robust (see #585)

packages/codemirror-blocks/spec/drag-test.ts, packages/codemirror-blocks/src/edits/performEdits.ts
Fixes #597 
At least I think the bug I found is the same one being talked about in that issue. I wrote a test for the "acceptable" behavior since that seemed to be what was previously implemented. If we want to change it to the ideal behavior, that should probably be addressed in a separate issue with a separate PR.
The bug was introduced because we were mutating the order of edits when converting them to change objects, but then relying on that order for calculating focus, so it was using the focus behavior for deleting the dragged node rather than the focus behavior for editing the node that was dropped onto.
=> Fix drag/drop focusing for nodes with children
